namespace BerexQms.Domain.AiEngine.Enums;

/// <summary>
/// Tracks the lifecycle state of an AI recommendation.
/// </summary>
public enum AiRecommendationStatus
{
    /// <summary>Recommendation generated by the AI engine, awaiting human review.</summary>
    Generated = 1,

    /// <summary>Recommendation has been reviewed by a quality engineer or manager.</summary>
    Reviewed = 2,

    /// <summary>Recommendation has been accepted and acknowledged for action.</summary>
    Accepted = 3,

    /// <summary>Recommendation has been rejected as not applicable or incorrect.</summary>
    Rejected = 4,

    /// <summary>Recommendation has expired without action and is no longer relevant.</summary>
    Expired = 5,
}
